### ISSUE TITLE
Lesson learned from unit tests

### ISSUE THREAD

**Issue by bernt-matthias** [WorkflowConversion/CTDConverter#53]
This is the list of TODOs that I would like to cover in the near future:

- [x] CDATA for command and help: started here https://github.com/bernt-matthias/CTDConverter/commit/a9ea2588f44ec086a3cdd289ebb76ac6b644e144
- [x] optional string/int/... parameters dont get `optional="true"` its currently only set for parameters with restrictions  https://github.com/bernt-matthias/CTDConverter/commit/9ab3b25aacc8fa18f47cd915d0d4b308a7ac07a4
- [x] int/float without a default value currently are autoset to 0 -- needs manual cherry pick from https://github.com/WorkflowConversion/CTDConverter/pull/49
- [x] fix indentation of closing `#end if` for the `#if str(...)` and the `-parameter`, https://github.com/bernt-matthias/CTDConverter/commit/eb50cfa7aeffed0757feb539a926ff8941966076
- [ ] there may be different ways to specify itemlists on the cli: `-param A B C` or `-param A -param B -param C`, see https://github.com/OpenMS/OpenMS/issues/4196, but in OpenMS only the former is used. 
- [ ] add the possibility to add hidden parameters
- `<item type='boolean' >`
  - [ ] are possible in ctd v1.7 
- `<item type='string' restriction="true,false">`
  - [x] booleans are rendered as select buttons https://github.com/bernt-matthias/CTDConverter/commit/51ab4499d3effb642f4b63d752708bd0fccd6e60
- `<item type='string' restriction="...,...,...">` and `<itemlist type='string' restriction="...,...,...">`
  - [x] itemlist with restrictions should be a select, not it is a repeat, https://github.com/bernt-matthias/CTDConverter/commit/9ab3b25aacc8fa18f47cd915d0d4b308a7ac07a4
  - [x] I would prefer non-radio selects .. lets keep radio up to 4 options
  - [ ] Do text and select inputs need the sanitizer (selects definitely can contain weird characters)
  - [x] selects with default select the option and a value="default" (redundant), https://github.com/bernt-matthias/CTDConverter/commit/12fe492a25894e9a2b5022f5b824caccb0ae816b
  - [x] select: cheetah can probably be simplified by using `'$param_param_wodefault_mandatory_restricted'` instead of the inner if, https://github.com/bernt-matthias/CTDConverter/commit/9ab3b25aacc8fa18f47cd915d0d4b308a7ac07a4
- [x] `<itemlist type='string/int/float'>` are currently rendered as repeat, which does not allow for default values. the best seems to be render them as comma separated list of elements with appropriate validators and sanitizers. https://github.com/bernt-matthias/CTDConverter/commit/ed73ced5cf7209317373665b142d4fa19bdc5f7b
  - [x] if default value(s) are given `max=1` is set?
  - [x] defaults are not set as repeat elements, but as `value="A B"`
  - [x] int and float repeats are rendered as text
  - [ ] 
- *Input files*
  - [x] input file variables need quoting https://github.com/bernt-matthias/CTDConverter/commit/bcb9986931ff55f031d4c106622b4ba4fcf239c9
  - [x] optional multiple inputs need an if statement
  - [x] multiple inputs (ITEMLIST) do not need a sanitizer https://github.com/bernt-matthias/CTDConverter/commit/f134d268cf4042fb29052dca74ba71286460abde
  - [x] link input files (in particular those with multiple possible formats) using the actual extension? https://github.com/bernt-matthias/CTDConverter/commit/85a366334dbc6f20cc2a386d928829340493eee9
  - [x] if multiple ctd formats map to the same galaxy format we get `format="txt,txt,txt"` https://github.com/bernt-matthias/CTDConverter/commit/e4b4333be54d6052a1eaf33f47665f6399484108
- *Output files*
  - [x] all output files need quoting https://github.com/bernt-matthias/CTDConverter/commit/bcb9986931ff55f031d4c106622b4ba4fcf239c9
  - [x] optional output files? -> add boolean to inputs and filter to the output https://github.com/bernt-matthias/CTDConverter/commit/5873f96460a07bdff59c1dd4a2138a9b2e791a4b
  - [ ] do output files (with a single possible format) need to have the correct extension?
  - [ ] output files allowing multiple formats currently just set one
    - if there is an input with the same supported formats (maybe check if its only one input to be sure) then set it as format_source
    - otherwise a select box for the user which to choose
  - [ ] multiple output files (needs to be the same number as for a specific input in most cases .. seems difficult to determine)
    - maybe check if there is only a single input or have an additional tabular config for controling this
  - [x] Can output parameters be black listed? Seems not possible to black list `param_stdout` (seems absent automatically if there are outputs)
- [x] Use `{# ' '.join([\"'%s'\"%str(_) for _ in " + actual_parameter + "])}` instead of tmp variable in command block for list selection, maybe also for multiple file input (by adding an `if _ != None` ), also all references to repeats could be removed from there. https://github.com/bernt-matthias/CTDConverter/commit/bcb9986931ff55f031d4c106622b4ba4fcf239c9
- [ ] tests?
  - [ ] remove `macro="..."` from conditional there for add the conditional select param
  - [x] implement the generation of simple test(s) for the test cases: setting all mandatory options wo defaults https://github.com/bernt-matthias/CTDConverter/commit/7d22fad1f661a8b3e4d8b49ca169c3ea635f8fc7
  - [ ] use the same code to extract a `<test>` (ie. remove all the rest) from the ctd files in the OpenMS tests
- [ ] implement `<NODE>` in tests (and render as section?)

- [ ] OpenMS has parameters specifying prefixes for output files, e.g. DTAExtractor.ctd       `<ITEM name="out" value="" type="string" description="base name of DTA output files (RT, m/z and extension are appended)" required="true" advanced="false" />`
- [ ] data type mapping
  - [ ] TOFCalibration `tof_const` parameter (OpenMS expects csv) works only if the file extension is absent or csv -> maybe remove extension for tabular or hardcode to csv (the former might be easier for tests because test data is detected as text)

**Comment by jpfeuffer** [comment]
Since a few weeks, OpenMS supports the bool type of CTD 1.7 as well:
Flags (with default value "false" which are given just as "-flag" on the CL) are written as <item type='bool' ...>
Boolean options (with default value "true" which are e.g. given as "-weirdflag false") will still be <item type='string' restrictions="true,false">

**Comment by bernt-matthias** [comment]
> Flags (with default value "false" which are given just as "-flag" on the CL) are written as <item type='bool' ...>

good to know. will add a test for this case.
