### ISSUE TITLE
restructure python package

### ISSUE THREAD

**Issue by bernt-matthias** [WorkflowConversion/CTDConverter#58]
If one pip installs this project it creates: `common`, `galaxy`, and `cwl` directly in the python dictribution. Would be nice to have all those modules in one folder, e.g. `ctdconverter/common`.

**Comment by mr-c** [comment]
I started this already at https://github.com/WorkflowConversion/CTDConverter/pull/56/commits/4ab09edb0fd0020b4360d0aba16abba95efd260b ; but feel free to pull that out and finish it ; the galaxy tests are giving me difficulties

**Comment by bernt-matthias** [comment]
Wonderful. I can have a look on the Galaxy tests.

**Comment by mr-c** [comment]
@bernt-matthias I redid that commit and pushed a branch to https://github.com/WorkflowConversion/CTDConverter/tree/layout_package ; we can collaborate there

**Comment by bernt-matthias** [comment]
OK. Could you open a PR for this branch? Then its easier to communicate. 

I think it would also be good if we would have a task list such that we can work together without creating to many conflicts.

**Comment by mr-c** [comment]
https://github.com/WorkflowConversion/CTDConverter/pull/59

> I think it would also be good if we would have a task list such that we can work together without creating to many conflicts.

Agreed!

**Comment by mr-c** [comment]
Fixed in #59
