### ISSUE TITLE
Make a new release 

### ISSUE THREAD

**Issue by bernt-matthias** [WorkflowConversion/CTDConverter#62]
Then we can have a conda package https://github.com/conda-forge/staged-recipes/pull/14908

**Comment by a-detiste** [comment]
Please tag a release to allow 2to3 removal (It's gone with Python3.13)

**Comment by mr-c** [comment]
https://github.com/WorkflowConversion/CTDConverter/releases/tag/v3.0a1 Totally untested, let us know!
